///////////////////////////////////////////////////////////////////////////////
//
// This file was automatically generated by RANOREX.
// DO NOT MODIFY THIS FILE! It is regenerated by the designer.
// All your modifications will be lost!
// http://www.ranorex.com
//
///////////////////////////////////////////////////////////////////////////////

using System;
using System.Collections.Generic;
using System.Text;
using System.Text.RegularExpressions;
using System.Drawing;
using System.Threading;
using WinForms = System.Windows.Forms;

using Ranorex;
using Ranorex.Core;
using Ranorex.Core.Testing;
using Ranorex.Core.Repository;

namespace MyTest25
{
#pragma warning disable 0436 //(CS0436) The type 'type' in 'assembly' conflicts with the imported type 'type2' in 'assembly'. Using the type defined in 'assembly'.
    /// <summary>
    ///The BirdPainting recording.
    /// </summary>
    [TestModule("2e96786e-05f5-468f-89d8-37c276f0d96d", ModuleType.Recording, 1)]
    public partial class BirdPainting : ITestModule
    {
        /// <summary>
        /// Holds an instance of the MyTest25Repository repository.
        /// </summary>
        public static MyTest25Repository repo = MyTest25Repository.Instance;

        static BirdPainting instance = new BirdPainting();

        /// <summary>
        /// Constructs a new instance.
        /// </summary>
        public BirdPainting()
        {
        }

        /// <summary>
        /// Gets a static instance of this recording.
        /// </summary>
        public static BirdPainting Instance
        {
            get { return instance; }
        }

#region Variables

#endregion

        /// <summary>
        /// Starts the replay of the static recording <see cref="Instance"/>.
        /// </summary>
        [System.CodeDom.Compiler.GeneratedCode("Ranorex", global::Ranorex.Core.Constants.CodeGenVersion)]
        public static void Start()
        {
            TestModuleRunner.Run(Instance);
        }

        /// <summary>
        /// Performs the playback of actions in this recording.
        /// </summary>
        /// <remarks>You should not call this method directly, instead pass the module
        /// instance to the <see cref="TestModuleRunner.Run(ITestModule)"/> method
        /// that will in turn invoke this method.</remarks>
        [System.CodeDom.Compiler.GeneratedCode("Ranorex", global::Ranorex.Core.Constants.CodeGenVersion)]
        void ITestModule.Run()
        {
            Mouse.DefaultMoveTime = 300;
            Keyboard.DefaultKeyPressTime = 20;
            Delay.SpeedFactor = 1.00;

            Init();

            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'UntitledPaint.Afx00007FF6BFC400008' at 228;153.", repo.UntitledPaint.Afx00007FF6BFC400008Info, new RecordItemIndex(0));
            repo.UntitledPaint.Afx00007FF6BFC400008.Click("228;153");
            Delay.Milliseconds(14950);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Down item 'UntitledPaint.Afx00007FF72AF900008' at 26;19.", repo.UntitledPaint.Afx00007FF72AF900008Info, new RecordItemIndex(1));
            repo.UntitledPaint.Afx00007FF72AF900008.MoveTo(new Location(Afx00007FF72AF900008_Screenshot1, "26;19", Afx00007FF72AF900008_Screenshot1_Options));
            Mouse.ButtonDown(System.Windows.Forms.MouseButtons.Left);
            Delay.Milliseconds(0);
            
        }

#region Image Feature Data
        /// <summary>
        /// DO NOT REFERENCE THIS CODE  - auto generated
        /// </summary>
        CompressedImage Afx00007FF72AF900008_Screenshot1
        { get { return repo.UntitledPaint.Afx00007FF72AF900008Info.GetScreenshot1(new Rectangle(183, 96, 56, 35)); } }

        /// <summary>
        /// DO NOT REFERENCE THIS CODE  - auto generated
        /// </summary>
        Imaging.FindOptions Afx00007FF72AF900008_Screenshot1_Options
        { get { return Imaging.FindOptions.Default; } }

#endregion
    }
#pragma warning restore 0436
}
