///////////////////////////////////////////////////////////////////////////////
//
// This file was automatically generated by RANOREX.
// DO NOT MODIFY THIS FILE! It is regenerated by the designer.
// All your modifications will be lost!
// http://www.ranorex.com
//
///////////////////////////////////////////////////////////////////////////////

using System;
using System.Collections.Generic;
using System.Text;
using System.Text.RegularExpressions;
using System.Drawing;
using System.Threading;
using WinForms = System.Windows.Forms;

using Ranorex;
using Ranorex.Core;
using Ranorex.Core.Testing;
using Ranorex.Core.Repository;

namespace MyTest25
{
#pragma warning disable 0436 //(CS0436) The type 'type' in 'assembly' conflicts with the imported type 'type2' in 'assembly'. Using the type defined in 'assembly'.
    /// <summary>
    ///The FileUpload recording.
    /// </summary>
    [TestModule("7d69fd26-5df8-4f4e-95ed-d8ce3c4dca1d", ModuleType.Recording, 1)]
    public partial class FileUpload : ITestModule
    {
        /// <summary>
        /// Holds an instance of the MyTest25Repository repository.
        /// </summary>
        public static MyTest25Repository repo = MyTest25Repository.Instance;

        static FileUpload instance = new FileUpload();

        /// <summary>
        /// Constructs a new instance.
        /// </summary>
        public FileUpload()
        {
        }

        /// <summary>
        /// Gets a static instance of this recording.
        /// </summary>
        public static FileUpload Instance
        {
            get { return instance; }
        }

#region Variables

#endregion

        /// <summary>
        /// Starts the replay of the static recording <see cref="Instance"/>.
        /// </summary>
        [System.CodeDom.Compiler.GeneratedCode("Ranorex", global::Ranorex.Core.Constants.CodeGenVersion)]
        public static void Start()
        {
            TestModuleRunner.Run(Instance);
        }

        /// <summary>
        /// Performs the playback of actions in this recording.
        /// </summary>
        /// <remarks>You should not call this method directly, instead pass the module
        /// instance to the <see cref="TestModuleRunner.Run(ITestModule)"/> method
        /// that will in turn invoke this method.</remarks>
        [System.CodeDom.Compiler.GeneratedCode("Ranorex", global::Ranorex.Core.Constants.CodeGenVersion)]
        void ITestModule.Run()
        {
            Mouse.DefaultMoveTime = 300;
            Keyboard.DefaultKeyPressTime = 20;
            Delay.SpeedFactor = 1.00;

            Init();

            Report.Log(ReportLevel.Info, "Application", "Run application 'C:\\Users\\Timothy McDoniel\\Documents\\Demo\\FileUpload.exe' in normal mode.", new RecordItemIndex(0));
            Host.Local.RunApplication("C:\\Users\\Timothy McDoniel\\Documents\\Demo\\FileUpload.exe", "", "C:\\Users\\Timothy McDoniel\\Documents\\Demo", false);
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'Form1.Button1' at 62;11.", repo.Form1.Button1Info, new RecordItemIndex(1));
            repo.Form1.Button1.Click("62;11");
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Wait", "Waiting 7m for the attribute 'Visible' to equal the specified value 'True'. Associated repository item: 'Form1.LbFinished'", repo.Form1.LbFinishedInfo, new RecordItemIndex(2));
            repo.Form1.LbFinishedInfo.WaitForAttributeEqual(420000, "Visible", "True");
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'Form1.BtResetUI' at 38;12.", repo.Form1.BtResetUIInfo, new RecordItemIndex(3));
            repo.Form1.BtResetUI.Click("38;12");
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'Form1.Close' at 31;15.", repo.Form1.CloseInfo, new RecordItemIndex(4));
            repo.Form1.Close.Click("31;15");
            Delay.Milliseconds(0);
            
        }

#region Image Feature Data
#endregion
    }
#pragma warning restore 0436
}
