///////////////////////////////////////////////////////////////////////////////
//
// This file was automatically generated by RANOREX.
// DO NOT MODIFY THIS FILE! It is regenerated by the designer.
// All your modifications will be lost!
// http://www.ranorex.com
//
///////////////////////////////////////////////////////////////////////////////

using System;
using System.Collections.Generic;
using System.Text;
using System.Drawing;
using Ranorex;
using Ranorex.Core;
using Ranorex.Core.Repository;
using Ranorex.Core.Testing;

namespace MyTest25
{
#pragma warning disable 0436 //(CS0436) The type 'type' in 'assembly' conflicts with the imported type 'type2' in 'assembly'. Using the type defined in 'assembly'.
    /// <summary>
    /// The class representing the MyTest25Repository element repository.
    /// </summary>
    [System.CodeDom.Compiler.GeneratedCode("Ranorex", global::Ranorex.Core.Constants.CodeGenVersion)]
    [RepositoryFolder("bc1d7cad-510f-49e8-8446-81c93f6be507")]
    public partial class MyTest25Repository : RepoGenBaseFolder
    {
        static MyTest25Repository instance = new MyTest25Repository();
        MyTest25RepositoryFolders.RxMainFrameAppFolder _rxmainframe;
        MyTest25RepositoryFolders.List1000AppFolder _list1000;
        MyTest25RepositoryFolders.Form1AppFolder _form1;
        MyTest25RepositoryFolders.UntitledPaintAppFolder _untitledpaint;

        /// <summary>
        /// Gets the singleton class instance representing the MyTest25Repository element repository.
        /// </summary>
        [RepositoryFolder("bc1d7cad-510f-49e8-8446-81c93f6be507")]
        public static MyTest25Repository Instance
        {
            get { return instance; }
        }

        /// <summary>
        /// Repository class constructor.
        /// </summary>
        public MyTest25Repository() 
            : base("MyTest25Repository", "/", null, 0, false, "bc1d7cad-510f-49e8-8446-81c93f6be507", ".\\RepositoryImages\\MyTest25Repositorybc1d7cad.rximgres")
        {
            _rxmainframe = new MyTest25RepositoryFolders.RxMainFrameAppFolder(this);
            _list1000 = new MyTest25RepositoryFolders.List1000AppFolder(this);
            _form1 = new MyTest25RepositoryFolders.Form1AppFolder(this);
            _untitledpaint = new MyTest25RepositoryFolders.UntitledPaintAppFolder(this);
        }

#region Variables

#endregion

        /// <summary>
        /// The Self item info.
        /// </summary>
        [RepositoryItemInfo("bc1d7cad-510f-49e8-8446-81c93f6be507")]
        public virtual RepoItemInfo SelfInfo
        {
            get
            {
                return _selfInfo;
            }
        }

        /// <summary>
        /// The RxMainFrame folder.
        /// </summary>
        [RepositoryFolder("839c1397-5ec2-448e-8e5a-0edd024dce5e")]
        public virtual MyTest25RepositoryFolders.RxMainFrameAppFolder RxMainFrame
        {
            get { return _rxmainframe; }
        }

        /// <summary>
        /// The List1000 folder.
        /// </summary>
        [RepositoryFolder("32b1a9db-6a17-4087-aa15-166005ea38a4")]
        public virtual MyTest25RepositoryFolders.List1000AppFolder List1000
        {
            get { return _list1000; }
        }

        /// <summary>
        /// The Form1 folder.
        /// </summary>
        [RepositoryFolder("c340ae87-34b3-4734-a4be-848fc4a39536")]
        public virtual MyTest25RepositoryFolders.Form1AppFolder Form1
        {
            get { return _form1; }
        }

        /// <summary>
        /// The UntitledPaint folder.
        /// </summary>
        [RepositoryFolder("d140ff2b-4627-45c6-997d-576280c1c769")]
        public virtual MyTest25RepositoryFolders.UntitledPaintAppFolder UntitledPaint
        {
            get { return _untitledpaint; }
        }
    }

    /// <summary>
    /// Inner folder classes.
    /// </summary>
    [System.CodeDom.Compiler.GeneratedCode("Ranorex", global::Ranorex.Core.Constants.CodeGenVersion)]
    public partial class MyTest25RepositoryFolders
    {
        /// <summary>
        /// The RxMainFrameAppFolder folder.
        /// </summary>
        [RepositoryFolder("839c1397-5ec2-448e-8e5a-0edd024dce5e")]
        public partial class RxMainFrameAppFolder : RepoGenBaseFolder
        {
            MyTest25RepositoryFolders.RxTabStandardFolder _rxtabstandard;
            MyTest25RepositoryFolders.NewFolderFolder _newfolder;
            RepoItemInfo _btnaddpersonInfo;
            RepoItemInfo _chkshowimageInfo;

            /// <summary>
            /// Creates a new RxMainFrame  folder.
            /// </summary>
            public RxMainFrameAppFolder(RepoGenBaseFolder parentFolder) :
                    base("RxMainFrame", "/form[@controlname='RxMainFrame']", parentFolder, 30000, null, true, "839c1397-5ec2-448e-8e5a-0edd024dce5e", "")
            {
                _rxtabstandard = new MyTest25RepositoryFolders.RxTabStandardFolder(this);
                _newfolder = new MyTest25RepositoryFolders.NewFolderFolder(this);
                _btnaddpersonInfo = new RepoItemInfo(this, "BtnAddPerson", "?/?/tabpage[@controlname='RxTabStandard']/button[@controlname='btnAddPerson']", "", 30000, null, "ab2fc2e9-67fa-473a-8659-7668560bc59a");
                _chkshowimageInfo = new RepoItemInfo(this, "ChkShowImage", "?/?/tabpage[@controlname='RxTabImageBased']/checkbox[@controlname='chkShowImage']", "", 30000, null, "10e8cd60-ffb7-43cc-a944-8ba1913e4edf");
            }

            /// <summary>
            /// The Self item.
            /// </summary>
            [RepositoryItem("839c1397-5ec2-448e-8e5a-0edd024dce5e")]
            public virtual Ranorex.Form Self
            {
                get
                {
                    return _selfInfo.CreateAdapter<Ranorex.Form>(true);
                }
            }

            /// <summary>
            /// The Self item info.
            /// </summary>
            [RepositoryItemInfo("839c1397-5ec2-448e-8e5a-0edd024dce5e")]
            public virtual RepoItemInfo SelfInfo
            {
                get
                {
                    return _selfInfo;
                }
            }

            /// <summary>
            /// The BtnAddPerson item.
            /// </summary>
            [RepositoryItem("ab2fc2e9-67fa-473a-8659-7668560bc59a")]
            public virtual Ranorex.Button BtnAddPerson
            {
                get
                {
                    return _btnaddpersonInfo.CreateAdapter<Ranorex.Button>(true);
                }
            }

            /// <summary>
            /// The BtnAddPerson item info.
            /// </summary>
            [RepositoryItemInfo("ab2fc2e9-67fa-473a-8659-7668560bc59a")]
            public virtual RepoItemInfo BtnAddPersonInfo
            {
                get
                {
                    return _btnaddpersonInfo;
                }
            }

            /// <summary>
            /// The ChkShowImage item.
            /// </summary>
            [RepositoryItem("10e8cd60-ffb7-43cc-a944-8ba1913e4edf")]
            public virtual Ranorex.CheckBox ChkShowImage
            {
                get
                {
                    return _chkshowimageInfo.CreateAdapter<Ranorex.CheckBox>(true);
                }
            }

            /// <summary>
            /// The ChkShowImage item info.
            /// </summary>
            [RepositoryItemInfo("10e8cd60-ffb7-43cc-a944-8ba1913e4edf")]
            public virtual RepoItemInfo ChkShowImageInfo
            {
                get
                {
                    return _chkshowimageInfo;
                }
            }

            /// <summary>
            /// The RxTabStandard folder.
            /// </summary>
            [RepositoryFolder("459c1516-cd0b-4fb7-802f-bd95a69434dc")]
            public virtual MyTest25RepositoryFolders.RxTabStandardFolder RxTabStandard
            {
                get { return _rxtabstandard; }
            }

            /// <summary>
            /// The NewFolder folder.
            /// </summary>
            [RepositoryFolder("5c932f3c-1a97-413d-93d8-ab71a4881d84")]
            public virtual MyTest25RepositoryFolders.NewFolderFolder NewFolder
            {
                get { return _newfolder; }
            }
        }

        /// <summary>
        /// The RxTabStandardFolder folder.
        /// </summary>
        [RepositoryFolder("459c1516-cd0b-4fb7-802f-bd95a69434dc")]
        public partial class RxTabStandardFolder : RepoGenBaseFolder
        {
            RepoItemInfo _closeInfo;
            RepoItemInfo _openInfo;
            RepoItemInfo _rdbmaleInfo;
            RepoItemInfo _firstnameInfo;
            RepoItemInfo _lastnameInfo;
            RepoItemInfo _text1001Info;
            RepoItemInfo _updowneditInfo;

            /// <summary>
            /// Creates a new RxTabStandard  folder.
            /// </summary>
            public RxTabStandardFolder(RepoGenBaseFolder parentFolder) :
                    base("RxTabStandard", "?/?/tabpage[@controlname='RxTabStandard']", parentFolder, 30000, null, false, "459c1516-cd0b-4fb7-802f-bd95a69434dc", "")
            {
                _closeInfo = new RepoItemInfo(this, "Close", "?/?/button[@accessiblename='Close']", "", 30000, null, "b269c0bd-27b0-4592-af76-cb8894cdfa6a");
                _openInfo = new RepoItemInfo(this, "Open", "?/?/button[@accessiblename='Open']", "", 30000, null, "030ec6ba-6b97-44d6-99fd-7de1d1c6dcf8");
                _rdbmaleInfo = new RepoItemInfo(this, "RdbMale", "?/?/radiobutton[@controlname='rdbMale']", "", 30000, null, "8926950f-a43e-4c5d-a3ef-89f3497ad3a5");
                _firstnameInfo = new RepoItemInfo(this, "FirstName", "?/?/text[@accessiblename='First name']", "", 30000, null, "0161bdeb-5b68-405c-bf19-87dc9b892c5a");
                _lastnameInfo = new RepoItemInfo(this, "LastName", "?/?/text[@accessiblename='Last name']", "", 30000, null, "c18942f9-528e-42c8-9e3f-dc3749e334ef");
                _text1001Info = new RepoItemInfo(this, "Text1001", "?/?/text[@controlid='1001']", "", 30000, null, "bc2aebaa-d69f-42ec-9fce-7957f65bd075");
                _updowneditInfo = new RepoItemInfo(this, "UpDownEdit", "?/?/text[@controlname='upDownEdit']", "", 30000, null, "abbf1801-6511-4e36-9724-fa0acfcd3a52");
            }

            /// <summary>
            /// The Self item.
            /// </summary>
            [RepositoryItem("459c1516-cd0b-4fb7-802f-bd95a69434dc")]
            public virtual Ranorex.TabPage Self
            {
                get
                {
                    return _selfInfo.CreateAdapter<Ranorex.TabPage>(true);
                }
            }

            /// <summary>
            /// The Self item info.
            /// </summary>
            [RepositoryItemInfo("459c1516-cd0b-4fb7-802f-bd95a69434dc")]
            public virtual RepoItemInfo SelfInfo
            {
                get
                {
                    return _selfInfo;
                }
            }

            /// <summary>
            /// The Close item.
            /// </summary>
            [RepositoryItem("b269c0bd-27b0-4592-af76-cb8894cdfa6a")]
            public virtual Ranorex.Button Close
            {
                get
                {
                    return _closeInfo.CreateAdapter<Ranorex.Button>(true);
                }
            }

            /// <summary>
            /// The Close item info.
            /// </summary>
            [RepositoryItemInfo("b269c0bd-27b0-4592-af76-cb8894cdfa6a")]
            public virtual RepoItemInfo CloseInfo
            {
                get
                {
                    return _closeInfo;
                }
            }

            /// <summary>
            /// The Open item.
            /// </summary>
            [RepositoryItem("030ec6ba-6b97-44d6-99fd-7de1d1c6dcf8")]
            public virtual Ranorex.Button Open
            {
                get
                {
                    return _openInfo.CreateAdapter<Ranorex.Button>(true);
                }
            }

            /// <summary>
            /// The Open item info.
            /// </summary>
            [RepositoryItemInfo("030ec6ba-6b97-44d6-99fd-7de1d1c6dcf8")]
            public virtual RepoItemInfo OpenInfo
            {
                get
                {
                    return _openInfo;
                }
            }

            /// <summary>
            /// The RdbMale item.
            /// </summary>
            [RepositoryItem("8926950f-a43e-4c5d-a3ef-89f3497ad3a5")]
            public virtual Ranorex.RadioButton RdbMale
            {
                get
                {
                    return _rdbmaleInfo.CreateAdapter<Ranorex.RadioButton>(true);
                }
            }

            /// <summary>
            /// The RdbMale item info.
            /// </summary>
            [RepositoryItemInfo("8926950f-a43e-4c5d-a3ef-89f3497ad3a5")]
            public virtual RepoItemInfo RdbMaleInfo
            {
                get
                {
                    return _rdbmaleInfo;
                }
            }

            /// <summary>
            /// The FirstName item.
            /// </summary>
            [RepositoryItem("0161bdeb-5b68-405c-bf19-87dc9b892c5a")]
            public virtual Ranorex.Text FirstName
            {
                get
                {
                    return _firstnameInfo.CreateAdapter<Ranorex.Text>(true);
                }
            }

            /// <summary>
            /// The FirstName item info.
            /// </summary>
            [RepositoryItemInfo("0161bdeb-5b68-405c-bf19-87dc9b892c5a")]
            public virtual RepoItemInfo FirstNameInfo
            {
                get
                {
                    return _firstnameInfo;
                }
            }

            /// <summary>
            /// The LastName item.
            /// </summary>
            [RepositoryItem("c18942f9-528e-42c8-9e3f-dc3749e334ef")]
            public virtual Ranorex.Text LastName
            {
                get
                {
                    return _lastnameInfo.CreateAdapter<Ranorex.Text>(true);
                }
            }

            /// <summary>
            /// The LastName item info.
            /// </summary>
            [RepositoryItemInfo("c18942f9-528e-42c8-9e3f-dc3749e334ef")]
            public virtual RepoItemInfo LastNameInfo
            {
                get
                {
                    return _lastnameInfo;
                }
            }

            /// <summary>
            /// The Text1001 item.
            /// </summary>
            [RepositoryItem("bc2aebaa-d69f-42ec-9fce-7957f65bd075")]
            public virtual Ranorex.Text Text1001
            {
                get
                {
                    return _text1001Info.CreateAdapter<Ranorex.Text>(true);
                }
            }

            /// <summary>
            /// The Text1001 item info.
            /// </summary>
            [RepositoryItemInfo("bc2aebaa-d69f-42ec-9fce-7957f65bd075")]
            public virtual RepoItemInfo Text1001Info
            {
                get
                {
                    return _text1001Info;
                }
            }

            /// <summary>
            /// The UpDownEdit item.
            /// </summary>
            [RepositoryItem("abbf1801-6511-4e36-9724-fa0acfcd3a52")]
            public virtual Ranorex.Text UpDownEdit
            {
                get
                {
                    return _updowneditInfo.CreateAdapter<Ranorex.Text>(true);
                }
            }

            /// <summary>
            /// The UpDownEdit item info.
            /// </summary>
            [RepositoryItemInfo("abbf1801-6511-4e36-9724-fa0acfcd3a52")]
            public virtual RepoItemInfo UpDownEditInfo
            {
                get
                {
                    return _updowneditInfo;
                }
            }
        }

        /// <summary>
        /// The NewFolderFolder folder.
        /// </summary>
        [RepositoryFolder("5c932f3c-1a97-413d-93d8-ab71a4881d84")]
        public partial class NewFolderFolder : RepoGenBaseFolder
        {

            /// <summary>
            /// Creates a new NewFolder  folder.
            /// </summary>
            public NewFolderFolder(RepoGenBaseFolder parentFolder) :
                    base("NewFolder", "", parentFolder, 0, null, false, "5c932f3c-1a97-413d-93d8-ab71a4881d84", "")
            {
            }

            /// <summary>
            /// The Self item info.
            /// </summary>
            [RepositoryItemInfo("5c932f3c-1a97-413d-93d8-ab71a4881d84")]
            public virtual RepoItemInfo SelfInfo
            {
                get
                {
                    return _selfInfo;
                }
            }
        }

        /// <summary>
        /// The List1000AppFolder folder.
        /// </summary>
        [RepositoryFolder("32b1a9db-6a17-4087-aa15-166005ea38a4")]
        public partial class List1000AppFolder : RepoGenBaseFolder
        {
            RepoItemInfo _marketingInfo;

            /// <summary>
            /// Creates a new List1000  folder.
            /// </summary>
            public List1000AppFolder(RepoGenBaseFolder parentFolder) :
                    base("List1000", "/list[@controlid='1000']", parentFolder, 30000, null, true, "32b1a9db-6a17-4087-aa15-166005ea38a4", "")
            {
                _marketingInfo = new RepoItemInfo(this, "Marketing", "listitem[@text='Marketing']", "", 30000, null, "3ad0fe91-9754-44bb-b939-b94efc62f8ef");
            }

            /// <summary>
            /// The Self item.
            /// </summary>
            [RepositoryItem("32b1a9db-6a17-4087-aa15-166005ea38a4")]
            public virtual Ranorex.List Self
            {
                get
                {
                    return _selfInfo.CreateAdapter<Ranorex.List>(true);
                }
            }

            /// <summary>
            /// The Self item info.
            /// </summary>
            [RepositoryItemInfo("32b1a9db-6a17-4087-aa15-166005ea38a4")]
            public virtual RepoItemInfo SelfInfo
            {
                get
                {
                    return _selfInfo;
                }
            }

            /// <summary>
            /// The Marketing item.
            /// </summary>
            [RepositoryItem("3ad0fe91-9754-44bb-b939-b94efc62f8ef")]
            public virtual Ranorex.ListItem Marketing
            {
                get
                {
                    return _marketingInfo.CreateAdapter<Ranorex.ListItem>(true);
                }
            }

            /// <summary>
            /// The Marketing item info.
            /// </summary>
            [RepositoryItemInfo("3ad0fe91-9754-44bb-b939-b94efc62f8ef")]
            public virtual RepoItemInfo MarketingInfo
            {
                get
                {
                    return _marketingInfo;
                }
            }
        }

        /// <summary>
        /// The Form1AppFolder folder.
        /// </summary>
        [RepositoryFolder("c340ae87-34b3-4734-a4be-848fc4a39536")]
        public partial class Form1AppFolder : RepoGenBaseFolder
        {
            RepoItemInfo _button1Info;
            RepoItemInfo _btresetuiInfo;
            RepoItemInfo _closeInfo;
            RepoItemInfo _lbfinishedInfo;

            /// <summary>
            /// Creates a new Form1  folder.
            /// </summary>
            public Form1AppFolder(RepoGenBaseFolder parentFolder) :
                    base("Form1", "/form[@controlname='Form1']", parentFolder, 30000, null, true, "c340ae87-34b3-4734-a4be-848fc4a39536", "")
            {
                _button1Info = new RepoItemInfo(this, "Button1", "button[@controlname='button1']", "", 30000, null, "8b93dff3-8c94-4be4-b43e-3a7c2616061e");
                _btresetuiInfo = new RepoItemInfo(this, "BtResetUI", "button[@controlname='btResetUI']", "", 30000, null, "0bae522b-89ba-4b92-bfe0-9f081094866b");
                _closeInfo = new RepoItemInfo(this, "Close", "?/?/button[@accessiblename='Close']", "", 30000, null, "d52e652a-8860-4c36-b5cd-33817b6b86f3");
                _lbfinishedInfo = new RepoItemInfo(this, "LbFinished", "text[@controlname='lbFinished']", "", 30000, null, "42e0763f-e243-4182-96e9-33e971419700");
            }

            /// <summary>
            /// The Self item.
            /// </summary>
            [RepositoryItem("c340ae87-34b3-4734-a4be-848fc4a39536")]
            public virtual Ranorex.Form Self
            {
                get
                {
                    return _selfInfo.CreateAdapter<Ranorex.Form>(true);
                }
            }

            /// <summary>
            /// The Self item info.
            /// </summary>
            [RepositoryItemInfo("c340ae87-34b3-4734-a4be-848fc4a39536")]
            public virtual RepoItemInfo SelfInfo
            {
                get
                {
                    return _selfInfo;
                }
            }

            /// <summary>
            /// The Button1 item.
            /// </summary>
            [RepositoryItem("8b93dff3-8c94-4be4-b43e-3a7c2616061e")]
            public virtual Ranorex.Button Button1
            {
                get
                {
                    return _button1Info.CreateAdapter<Ranorex.Button>(true);
                }
            }

            /// <summary>
            /// The Button1 item info.
            /// </summary>
            [RepositoryItemInfo("8b93dff3-8c94-4be4-b43e-3a7c2616061e")]
            public virtual RepoItemInfo Button1Info
            {
                get
                {
                    return _button1Info;
                }
            }

            /// <summary>
            /// The BtResetUI item.
            /// </summary>
            [RepositoryItem("0bae522b-89ba-4b92-bfe0-9f081094866b")]
            public virtual Ranorex.Button BtResetUI
            {
                get
                {
                    return _btresetuiInfo.CreateAdapter<Ranorex.Button>(true);
                }
            }

            /// <summary>
            /// The BtResetUI item info.
            /// </summary>
            [RepositoryItemInfo("0bae522b-89ba-4b92-bfe0-9f081094866b")]
            public virtual RepoItemInfo BtResetUIInfo
            {
                get
                {
                    return _btresetuiInfo;
                }
            }

            /// <summary>
            /// The Close item.
            /// </summary>
            [RepositoryItem("d52e652a-8860-4c36-b5cd-33817b6b86f3")]
            public virtual Ranorex.Button Close
            {
                get
                {
                    return _closeInfo.CreateAdapter<Ranorex.Button>(true);
                }
            }

            /// <summary>
            /// The Close item info.
            /// </summary>
            [RepositoryItemInfo("d52e652a-8860-4c36-b5cd-33817b6b86f3")]
            public virtual RepoItemInfo CloseInfo
            {
                get
                {
                    return _closeInfo;
                }
            }

            /// <summary>
            /// The LbFinished item.
            /// </summary>
            [RepositoryItem("42e0763f-e243-4182-96e9-33e971419700")]
            public virtual Ranorex.Text LbFinished
            {
                get
                {
                    return _lbfinishedInfo.CreateAdapter<Ranorex.Text>(true);
                }
            }

            /// <summary>
            /// The LbFinished item info.
            /// </summary>
            [RepositoryItemInfo("42e0763f-e243-4182-96e9-33e971419700")]
            public virtual RepoItemInfo LbFinishedInfo
            {
                get
                {
                    return _lbfinishedInfo;
                }
            }
        }

        /// <summary>
        /// The UntitledPaintAppFolder folder.
        /// </summary>
        [RepositoryFolder("d140ff2b-4627-45c6-997d-576280c1c769")]
        public partial class UntitledPaintAppFolder : RepoGenBaseFolder
        {
            RepoItemInfo _afx00007ff6bfc400008Info;
            Afx00007FF72AF900008InfoClass _afx00007ff72af900008Info;

            /// <summary>
            /// Creates a new UntitledPaint  folder.
            /// </summary>
            public UntitledPaintAppFolder(RepoGenBaseFolder parentFolder) :
                    base("UntitledPaint", "/form[@title='Untitled - Paint']", parentFolder, 30000, null, true, "d140ff2b-4627-45c6-997d-576280c1c769", "")
            {
                _afx00007ff6bfc400008Info = new RepoItemInfo(this, "Afx00007FF6BFC400008", "?/?/element[@class='Afx:00007FF6BFC40000:8']", "", 30000, null, "a13f9411-76ef-47e2-b9b1-a441b7ab30bf");
                _afx00007ff72af900008Info = new Afx00007FF72AF900008InfoClass(this);
            }

            /// <summary>
            /// The Afx00007FF72AF900008InfoClass folder.
            /// </summary>
            [RepositoryItemInfo("d68915ed-98a4-464f-9509-ae702609012e")]
            public class Afx00007FF72AF900008InfoClass : RepoItemInfo
            {
                /// <summary>
                /// Afx00007FF72AF900008InfoClass class constructor.
                /// </summary>
                public Afx00007FF72AF900008InfoClass(RepoGenBaseFolder parentFolder)
                    : base(parentFolder, "Afx00007FF72AF900008", "?/?/element[@class='Afx:00007FF72AF90000:8']", 30000, null, "d68915ed-98a4-464f-9509-ae702609012e")
                { }

                /// <summary>
                /// Gets the Screenshot1 item image.
                /// </summary>
                /// <returns>The Screenshot1 image.</returns>
                [RepositoryImage("3cf55e2c-df12-47a1-aab2-878cc7647352")]
                public CompressedImage GetScreenshot1()
                {
                    return GetImage("3cf55e2c-df12-47a1-aab2-878cc7647352");
                }

                /// <summary>
                /// Gets the Screenshot1 item image.
                /// </summary>
                /// <param name="cropRect">The bounds of the sub-image to return.</param>
                /// <returns>The cropped image.</returns>
                [RepositoryImage("3cf55e2c-df12-47a1-aab2-878cc7647352")]
                public CompressedImage GetScreenshot1(System.Drawing.Rectangle cropRect)
                {
                    return GetImage("3cf55e2c-df12-47a1-aab2-878cc7647352", cropRect);
                }
            }

            /// <summary>
            /// The Self item.
            /// </summary>
            [RepositoryItem("d140ff2b-4627-45c6-997d-576280c1c769")]
            public virtual Ranorex.Form Self
            {
                get
                {
                    return _selfInfo.CreateAdapter<Ranorex.Form>(true);
                }
            }

            /// <summary>
            /// The Self item info.
            /// </summary>
            [RepositoryItemInfo("d140ff2b-4627-45c6-997d-576280c1c769")]
            public virtual RepoItemInfo SelfInfo
            {
                get
                {
                    return _selfInfo;
                }
            }

            /// <summary>
            /// The Afx00007FF6BFC400008 item.
            /// </summary>
            [RepositoryItem("a13f9411-76ef-47e2-b9b1-a441b7ab30bf")]
            public virtual Ranorex.Unknown Afx00007FF6BFC400008
            {
                get
                {
                    return _afx00007ff6bfc400008Info.CreateAdapter<Ranorex.Unknown>(true);
                }
            }

            /// <summary>
            /// The Afx00007FF6BFC400008 item info.
            /// </summary>
            [RepositoryItemInfo("a13f9411-76ef-47e2-b9b1-a441b7ab30bf")]
            public virtual RepoItemInfo Afx00007FF6BFC400008Info
            {
                get
                {
                    return _afx00007ff6bfc400008Info;
                }
            }

            /// <summary>
            /// The Afx00007FF72AF900008 item.
            /// </summary>
            [RepositoryItem("d68915ed-98a4-464f-9509-ae702609012e")]
            public virtual Ranorex.Unknown Afx00007FF72AF900008
            {
                get
                {
                    return _afx00007ff72af900008Info.CreateAdapter<Ranorex.Unknown>(true);
                }
            }

            /// <summary>
            /// The Afx00007FF72AF900008 item info.
            /// </summary>
            [RepositoryItemInfo("d68915ed-98a4-464f-9509-ae702609012e")]
            public virtual Afx00007FF72AF900008InfoClass Afx00007FF72AF900008Info
            {
                get
                {
                    return _afx00007ff72af900008Info;
                }
            }
        }

    }
#pragma warning restore 0436
}
