///////////////////////////////////////////////////////////////////////////////
//
// This file was automatically generated by RANOREX.
// DO NOT MODIFY THIS FILE! It is regenerated by the designer.
// All your modifications will be lost!
// http://www.ranorex.com
//
///////////////////////////////////////////////////////////////////////////////

using System;
using System.Collections.Generic;
using System.Text;
using System.Drawing;
using Ranorex;
using Ranorex.Core;
using Ranorex.Core.Repository;
using Ranorex.Core.Testing;

namespace Demo3DS
{
#pragma warning disable 0436 //(CS0436) The type 'type' in 'assembly' conflicts with the imported type 'type2' in 'assembly'. Using the type defined in 'assembly'.
    /// <summary>
    /// The class representing the Demo3DSRepository element repository.
    /// </summary>
    [System.CodeDom.Compiler.GeneratedCode("Ranorex", global::Ranorex.Core.Constants.CodeGenVersion)]
    [RepositoryFolder("83d651f3-f932-480e-a2cd-97b86357971d")]
    public partial class Demo3DSRepository : RepoGenBaseFolder
    {
        static Demo3DSRepository instance = new Demo3DSRepository();
        Demo3DSRepositoryFolders.RxMainFrameAppFolder _rxmainframe;
        Demo3DSRepositoryFolders.AddEntryFolder _addentry;
        Demo3DSRepositoryFolders.SelectTabFolder _selecttab;
        Demo3DSRepositoryFolders.ValidateItemsFolder _validateitems;
        Demo3DSRepositoryFolders.Form1AppFolder _form1;

        /// <summary>
        /// Gets the singleton class instance representing the Demo3DSRepository element repository.
        /// </summary>
        [RepositoryFolder("83d651f3-f932-480e-a2cd-97b86357971d")]
        public static Demo3DSRepository Instance
        {
            get { return instance; }
        }

        /// <summary>
        /// Repository class constructor.
        /// </summary>
        public Demo3DSRepository() 
            : base("Demo3DSRepository", "/", null, 0, false, "83d651f3-f932-480e-a2cd-97b86357971d", ".\\RepositoryImages\\Demo3DSRepository83d651f3.rximgres")
        {
            _rxmainframe = new Demo3DSRepositoryFolders.RxMainFrameAppFolder(this);
            _addentry = new Demo3DSRepositoryFolders.AddEntryFolder(this);
            _selecttab = new Demo3DSRepositoryFolders.SelectTabFolder(this);
            _validateitems = new Demo3DSRepositoryFolders.ValidateItemsFolder(this);
            _form1 = new Demo3DSRepositoryFolders.Form1AppFolder(this);
        }

#region Variables

        string _varDepartment = "Testing";

        /// <summary>
        /// Gets or sets the value of variable varDepartment.
        /// </summary>
        [TestVariable("ee50d8d7-8cd8-4648-8c02-7a9ba6de13b5")]
        public string varDepartment
        {
            get { return _varDepartment; }
            set { _varDepartment = value; }
        }

        string _varGender = "rdbMale";

        /// <summary>
        /// Gets or sets the value of variable varGender.
        /// </summary>
        [TestVariable("a067eebf-5e2b-4389-b51c-d3881940387e")]
        public string varGender
        {
            get { return _varGender; }
            set { _varGender = value; }
        }

#endregion

        /// <summary>
        /// The Self item info.
        /// </summary>
        [RepositoryItemInfo("83d651f3-f932-480e-a2cd-97b86357971d")]
        public virtual RepoItemInfo SelfInfo
        {
            get
            {
                return _selfInfo;
            }
        }

        /// <summary>
        /// The RxMainFrame folder.
        /// </summary>
        [RepositoryFolder("1e27049b-4add-41c3-a887-a13005ec1fd1")]
        public virtual Demo3DSRepositoryFolders.RxMainFrameAppFolder RxMainFrame
        {
            get { return _rxmainframe; }
        }

        /// <summary>
        /// The AddEntry folder.
        /// </summary>
        [RepositoryFolder("515df4b5-dc2e-4f42-a085-2f86e1062f91")]
        public virtual Demo3DSRepositoryFolders.AddEntryFolder AddEntry
        {
            get { return _addentry; }
        }

        /// <summary>
        /// The SelectTab folder.
        /// </summary>
        [RepositoryFolder("137ee75b-7895-40ef-a0ca-85f5b2395bfe")]
        public virtual Demo3DSRepositoryFolders.SelectTabFolder SelectTab
        {
            get { return _selecttab; }
        }

        /// <summary>
        /// The ValidateItems folder.
        /// </summary>
        [RepositoryFolder("1901f645-95b2-47bb-920f-3942c6c16eb1")]
        public virtual Demo3DSRepositoryFolders.ValidateItemsFolder ValidateItems
        {
            get { return _validateitems; }
        }

        /// <summary>
        /// The Form1 folder.
        /// </summary>
        [RepositoryFolder("4ad5b588-098e-4368-b5c7-c0f340271864")]
        public virtual Demo3DSRepositoryFolders.Form1AppFolder Form1
        {
            get { return _form1; }
        }
    }

    /// <summary>
    /// Inner folder classes.
    /// </summary>
    [System.CodeDom.Compiler.GeneratedCode("Ranorex", global::Ranorex.Core.Constants.CodeGenVersion)]
    public partial class Demo3DSRepositoryFolders
    {
        /// <summary>
        /// The RxMainFrameAppFolder folder.
        /// </summary>
        [RepositoryFolder("1e27049b-4add-41c3-a887-a13005ec1fd1")]
        public partial class RxMainFrameAppFolder : RepoGenBaseFolder
        {

            /// <summary>
            /// Creates a new RxMainFrame  folder.
            /// </summary>
            public RxMainFrameAppFolder(RepoGenBaseFolder parentFolder) :
                    base("RxMainFrame", "/form[@controlname='RxMainFrame']", parentFolder, 30000, null, true, "1e27049b-4add-41c3-a887-a13005ec1fd1", "")
            {
            }

            /// <summary>
            /// The Self item.
            /// </summary>
            [RepositoryItem("1e27049b-4add-41c3-a887-a13005ec1fd1")]
            public virtual Ranorex.Form Self
            {
                get
                {
                    return _selfInfo.CreateAdapter<Ranorex.Form>(true);
                }
            }

            /// <summary>
            /// The Self item info.
            /// </summary>
            [RepositoryItemInfo("1e27049b-4add-41c3-a887-a13005ec1fd1")]
            public virtual RepoItemInfo SelfInfo
            {
                get
                {
                    return _selfInfo;
                }
            }
        }

        /// <summary>
        /// The AddEntryFolder folder.
        /// </summary>
        [RepositoryFolder("515df4b5-dc2e-4f42-a085-2f86e1062f91")]
        public partial class AddEntryFolder : RepoGenBaseFolder
        {
            RepoItemInfo _firstnamefieldInfo;
            RepoItemInfo _lastnamefieldInfo;
            RepoItemInfo _agefieldInfo;
            RepoItemInfo _deptdownbtnInfo;
            RepoItemInfo _genderradiobtnInfo;
            RepoItemInfo _addpersonbtnInfo;
            RepoItemInfo _departmentInfo;

            /// <summary>
            /// Creates a new AddEntry  folder.
            /// </summary>
            public AddEntryFolder(RepoGenBaseFolder parentFolder) :
                    base("AddEntry", "", parentFolder, 0, null, false, "515df4b5-dc2e-4f42-a085-2f86e1062f91", "")
            {
                _firstnamefieldInfo = new RepoItemInfo(this, "FirstNameField", "/form[@controlname='RxMainFrame']//text[@accessiblename='First name']", "", 30000, null, "e18999f1-0c94-4870-b42a-8a806c541dbc");
                _lastnamefieldInfo = new RepoItemInfo(this, "LastNameField", "/form[@controlname='RxMainFrame']//text[@accessiblename='Last name']", "", 30000, null, "88b9f1db-07d1-432b-aeea-5566618e220f");
                _agefieldInfo = new RepoItemInfo(this, "AgeField", "/form[@controlname='RxMainFrame']//text[@controlname='upDownEdit']", "", 30000, null, "ae8bf5f4-67e4-43f2-a2d1-b10bf1d0f7a9");
                _deptdownbtnInfo = new RepoItemInfo(this, "DeptDownBtn", "/form[@controlname='RxMainFrame']//button[@accessiblename='Open']", "", 30000, null, "cb633b9a-8610-4d54-920f-361d143b3f59");
                _genderradiobtnInfo = new RepoItemInfo(this, "GenderRadioBtn", "/form[@controlname='RxMainFrame']//radiobutton[@controlname=$varGender]", "", 30000, null, "806a0513-9fe0-4b7a-a12c-aa1542e2604a");
                _addpersonbtnInfo = new RepoItemInfo(this, "AddPersonBtn", "/form[@controlname='RxMainFrame']//button[@controlname='btnAddPerson']", "", 30000, null, "8d81e910-2622-42c1-90b8-81da7a3d79a7");
                _departmentInfo = new RepoItemInfo(this, "Department", "/list[@controlid='1000']/listitem[@text=$varDepartment]", "", 30000, null, "3a814bc5-2ced-474f-b1bc-62da3ac5e240");
            }

            /// <summary>
            /// The Self item info.
            /// </summary>
            [RepositoryItemInfo("515df4b5-dc2e-4f42-a085-2f86e1062f91")]
            public virtual RepoItemInfo SelfInfo
            {
                get
                {
                    return _selfInfo;
                }
            }

            /// <summary>
            /// The FirstNameField item.
            /// </summary>
            [RepositoryItem("e18999f1-0c94-4870-b42a-8a806c541dbc")]
            public virtual Ranorex.Text FirstNameField
            {
                get
                {
                    return _firstnamefieldInfo.CreateAdapter<Ranorex.Text>(true);
                }
            }

            /// <summary>
            /// The FirstNameField item info.
            /// </summary>
            [RepositoryItemInfo("e18999f1-0c94-4870-b42a-8a806c541dbc")]
            public virtual RepoItemInfo FirstNameFieldInfo
            {
                get
                {
                    return _firstnamefieldInfo;
                }
            }

            /// <summary>
            /// The LastNameField item.
            /// </summary>
            [RepositoryItem("88b9f1db-07d1-432b-aeea-5566618e220f")]
            public virtual Ranorex.Text LastNameField
            {
                get
                {
                    return _lastnamefieldInfo.CreateAdapter<Ranorex.Text>(true);
                }
            }

            /// <summary>
            /// The LastNameField item info.
            /// </summary>
            [RepositoryItemInfo("88b9f1db-07d1-432b-aeea-5566618e220f")]
            public virtual RepoItemInfo LastNameFieldInfo
            {
                get
                {
                    return _lastnamefieldInfo;
                }
            }

            /// <summary>
            /// The AgeField item.
            /// </summary>
            [RepositoryItem("ae8bf5f4-67e4-43f2-a2d1-b10bf1d0f7a9")]
            public virtual Ranorex.Text AgeField
            {
                get
                {
                    return _agefieldInfo.CreateAdapter<Ranorex.Text>(true);
                }
            }

            /// <summary>
            /// The AgeField item info.
            /// </summary>
            [RepositoryItemInfo("ae8bf5f4-67e4-43f2-a2d1-b10bf1d0f7a9")]
            public virtual RepoItemInfo AgeFieldInfo
            {
                get
                {
                    return _agefieldInfo;
                }
            }

            /// <summary>
            /// The DeptDownBtn item.
            /// </summary>
            [RepositoryItem("cb633b9a-8610-4d54-920f-361d143b3f59")]
            public virtual Ranorex.Button DeptDownBtn
            {
                get
                {
                    return _deptdownbtnInfo.CreateAdapter<Ranorex.Button>(true);
                }
            }

            /// <summary>
            /// The DeptDownBtn item info.
            /// </summary>
            [RepositoryItemInfo("cb633b9a-8610-4d54-920f-361d143b3f59")]
            public virtual RepoItemInfo DeptDownBtnInfo
            {
                get
                {
                    return _deptdownbtnInfo;
                }
            }

            /// <summary>
            /// The GenderRadioBtn item.
            /// </summary>
            [RepositoryItem("806a0513-9fe0-4b7a-a12c-aa1542e2604a")]
            public virtual Ranorex.RadioButton GenderRadioBtn
            {
                get
                {
                    return _genderradiobtnInfo.CreateAdapter<Ranorex.RadioButton>(true);
                }
            }

            /// <summary>
            /// The GenderRadioBtn item info.
            /// </summary>
            [RepositoryItemInfo("806a0513-9fe0-4b7a-a12c-aa1542e2604a")]
            public virtual RepoItemInfo GenderRadioBtnInfo
            {
                get
                {
                    return _genderradiobtnInfo;
                }
            }

            /// <summary>
            /// The AddPersonBtn item.
            /// </summary>
            [RepositoryItem("8d81e910-2622-42c1-90b8-81da7a3d79a7")]
            public virtual Ranorex.Button AddPersonBtn
            {
                get
                {
                    return _addpersonbtnInfo.CreateAdapter<Ranorex.Button>(true);
                }
            }

            /// <summary>
            /// The AddPersonBtn item info.
            /// </summary>
            [RepositoryItemInfo("8d81e910-2622-42c1-90b8-81da7a3d79a7")]
            public virtual RepoItemInfo AddPersonBtnInfo
            {
                get
                {
                    return _addpersonbtnInfo;
                }
            }

            /// <summary>
            /// The Department item.
            /// </summary>
            [RepositoryItem("3a814bc5-2ced-474f-b1bc-62da3ac5e240")]
            public virtual Ranorex.ListItem Department
            {
                get
                {
                    return _departmentInfo.CreateAdapter<Ranorex.ListItem>(true);
                }
            }

            /// <summary>
            /// The Department item info.
            /// </summary>
            [RepositoryItemInfo("3a814bc5-2ced-474f-b1bc-62da3ac5e240")]
            public virtual RepoItemInfo DepartmentInfo
            {
                get
                {
                    return _departmentInfo;
                }
            }
        }

        /// <summary>
        /// The SelectTabFolder folder.
        /// </summary>
        [RepositoryFolder("137ee75b-7895-40ef-a0ca-85f5b2395bfe")]
        public partial class SelectTabFolder : RepoGenBaseFolder
        {
            RepoItemInfo _testdatabaseInfo;

            /// <summary>
            /// Creates a new SelectTab  folder.
            /// </summary>
            public SelectTabFolder(RepoGenBaseFolder parentFolder) :
                    base("SelectTab", "", parentFolder, 0, null, false, "137ee75b-7895-40ef-a0ca-85f5b2395bfe", "")
            {
                _testdatabaseInfo = new RepoItemInfo(this, "TestDatabase", "/form[@controlname='RxMainFrame']/?/?/tabpage[@accessiblename='Test database']", "", 30000, null, "81d97216-bf88-46be-8935-4ec3a31036d9");
            }

            /// <summary>
            /// The Self item info.
            /// </summary>
            [RepositoryItemInfo("137ee75b-7895-40ef-a0ca-85f5b2395bfe")]
            public virtual RepoItemInfo SelfInfo
            {
                get
                {
                    return _selfInfo;
                }
            }

            /// <summary>
            /// The TestDatabase item.
            /// </summary>
            [RepositoryItem("81d97216-bf88-46be-8935-4ec3a31036d9")]
            public virtual Ranorex.TabPage TestDatabase
            {
                get
                {
                    return _testdatabaseInfo.CreateAdapter<Ranorex.TabPage>(true);
                }
            }

            /// <summary>
            /// The TestDatabase item info.
            /// </summary>
            [RepositoryItemInfo("81d97216-bf88-46be-8935-4ec3a31036d9")]
            public virtual RepoItemInfo TestDatabaseInfo
            {
                get
                {
                    return _testdatabaseInfo;
                }
            }
        }

        /// <summary>
        /// The ValidateItemsFolder folder.
        /// </summary>
        [RepositoryFolder("1901f645-95b2-47bb-920f-3942c6c16eb1")]
        public partial class ValidateItemsFolder : RepoGenBaseFolder
        {
            RepoItemInfo _lblnumberofpersonsnumberInfo;

            /// <summary>
            /// Creates a new ValidateItems  folder.
            /// </summary>
            public ValidateItemsFolder(RepoGenBaseFolder parentFolder) :
                    base("ValidateItems", "", parentFolder, 0, null, false, "1901f645-95b2-47bb-920f-3942c6c16eb1", "")
            {
                _lblnumberofpersonsnumberInfo = new RepoItemInfo(this, "LblNumberOfPersonsNumber", "/form[@controlname='RxMainFrame']//text[@controlname='lblNumberOfPersonsNumber']", "", 30000, null, "26fb437e-a2c2-4819-bb55-b8e60a95c4d3");
            }

            /// <summary>
            /// The Self item info.
            /// </summary>
            [RepositoryItemInfo("1901f645-95b2-47bb-920f-3942c6c16eb1")]
            public virtual RepoItemInfo SelfInfo
            {
                get
                {
                    return _selfInfo;
                }
            }

            /// <summary>
            /// The LblNumberOfPersonsNumber item.
            /// </summary>
            [RepositoryItem("26fb437e-a2c2-4819-bb55-b8e60a95c4d3")]
            public virtual Ranorex.Text LblNumberOfPersonsNumber
            {
                get
                {
                    return _lblnumberofpersonsnumberInfo.CreateAdapter<Ranorex.Text>(true);
                }
            }

            /// <summary>
            /// The LblNumberOfPersonsNumber item info.
            /// </summary>
            [RepositoryItemInfo("26fb437e-a2c2-4819-bb55-b8e60a95c4d3")]
            public virtual RepoItemInfo LblNumberOfPersonsNumberInfo
            {
                get
                {
                    return _lblnumberofpersonsnumberInfo;
                }
            }
        }

        /// <summary>
        /// The Form1AppFolder folder.
        /// </summary>
        [RepositoryFolder("4ad5b588-098e-4368-b5c7-c0f340271864")]
        public partial class Form1AppFolder : RepoGenBaseFolder
        {
            RepoItemInfo _button1Info;
            RepoItemInfo _btresetuiInfo;
            RepoItemInfo _lbfinishedInfo;
            RepoItemInfo _progressbar1Info;
            RepoItemInfo _lbprogressInfo;

            /// <summary>
            /// Creates a new Form1  folder.
            /// </summary>
            public Form1AppFolder(RepoGenBaseFolder parentFolder) :
                    base("Form1", "/form[@controlname='Form1']", parentFolder, 30000, null, true, "4ad5b588-098e-4368-b5c7-c0f340271864", "")
            {
                _button1Info = new RepoItemInfo(this, "Button1", "button[@controlname='button1']", "", 30000, null, "87f8b045-a6de-49d7-93f2-35e6d39d6579");
                _btresetuiInfo = new RepoItemInfo(this, "BtResetUI", "button[@controlname='btResetUI']", "", 30000, null, "ee0451eb-3105-4731-a5d6-53c664d86031");
                _lbfinishedInfo = new RepoItemInfo(this, "LbFinished", "text[@controlname='lbFinished']", "", 30000, null, "28072df4-9003-4ee3-afaf-1f1b77b65fae");
                _progressbar1Info = new RepoItemInfo(this, "ProgressBar1", "progressbar[@controlname='progressBar1']", "", 30000, null, "7144ef61-e8ca-4df0-9102-8d9bff66ea08");
                _lbprogressInfo = new RepoItemInfo(this, "LbProgress", "text[@controlname='lbProgress' and @text='100']", "", 30000, null, "c5f60713-1256-4df6-9805-3804efd55924");
            }

            /// <summary>
            /// The Self item.
            /// </summary>
            [RepositoryItem("4ad5b588-098e-4368-b5c7-c0f340271864")]
            public virtual Ranorex.Form Self
            {
                get
                {
                    return _selfInfo.CreateAdapter<Ranorex.Form>(true);
                }
            }

            /// <summary>
            /// The Self item info.
            /// </summary>
            [RepositoryItemInfo("4ad5b588-098e-4368-b5c7-c0f340271864")]
            public virtual RepoItemInfo SelfInfo
            {
                get
                {
                    return _selfInfo;
                }
            }

            /// <summary>
            /// The Button1 item.
            /// </summary>
            [RepositoryItem("87f8b045-a6de-49d7-93f2-35e6d39d6579")]
            public virtual Ranorex.Button Button1
            {
                get
                {
                    return _button1Info.CreateAdapter<Ranorex.Button>(true);
                }
            }

            /// <summary>
            /// The Button1 item info.
            /// </summary>
            [RepositoryItemInfo("87f8b045-a6de-49d7-93f2-35e6d39d6579")]
            public virtual RepoItemInfo Button1Info
            {
                get
                {
                    return _button1Info;
                }
            }

            /// <summary>
            /// The BtResetUI item.
            /// </summary>
            [RepositoryItem("ee0451eb-3105-4731-a5d6-53c664d86031")]
            public virtual Ranorex.Button BtResetUI
            {
                get
                {
                    return _btresetuiInfo.CreateAdapter<Ranorex.Button>(true);
                }
            }

            /// <summary>
            /// The BtResetUI item info.
            /// </summary>
            [RepositoryItemInfo("ee0451eb-3105-4731-a5d6-53c664d86031")]
            public virtual RepoItemInfo BtResetUIInfo
            {
                get
                {
                    return _btresetuiInfo;
                }
            }

            /// <summary>
            /// The LbFinished item.
            /// </summary>
            [RepositoryItem("28072df4-9003-4ee3-afaf-1f1b77b65fae")]
            public virtual Ranorex.Text LbFinished
            {
                get
                {
                    return _lbfinishedInfo.CreateAdapter<Ranorex.Text>(true);
                }
            }

            /// <summary>
            /// The LbFinished item info.
            /// </summary>
            [RepositoryItemInfo("28072df4-9003-4ee3-afaf-1f1b77b65fae")]
            public virtual RepoItemInfo LbFinishedInfo
            {
                get
                {
                    return _lbfinishedInfo;
                }
            }

            /// <summary>
            /// The ProgressBar1 item.
            /// </summary>
            [RepositoryItem("7144ef61-e8ca-4df0-9102-8d9bff66ea08")]
            public virtual Ranorex.ProgressBar ProgressBar1
            {
                get
                {
                    return _progressbar1Info.CreateAdapter<Ranorex.ProgressBar>(true);
                }
            }

            /// <summary>
            /// The ProgressBar1 item info.
            /// </summary>
            [RepositoryItemInfo("7144ef61-e8ca-4df0-9102-8d9bff66ea08")]
            public virtual RepoItemInfo ProgressBar1Info
            {
                get
                {
                    return _progressbar1Info;
                }
            }

            /// <summary>
            /// The LbProgress item.
            /// </summary>
            [RepositoryItem("c5f60713-1256-4df6-9805-3804efd55924")]
            public virtual Ranorex.Text LbProgress
            {
                get
                {
                    return _lbprogressInfo.CreateAdapter<Ranorex.Text>(true);
                }
            }

            /// <summary>
            /// The LbProgress item info.
            /// </summary>
            [RepositoryItemInfo("c5f60713-1256-4df6-9805-3804efd55924")]
            public virtual RepoItemInfo LbProgressInfo
            {
                get
                {
                    return _lbprogressInfo;
                }
            }
        }

    }
#pragma warning restore 0436
}
