///////////////////////////////////////////////////////////////////////////////
//
// This file was automatically generated by RANOREX.
// DO NOT MODIFY THIS FILE! It is regenerated by the designer.
// All your modifications will be lost!
// http://www.ranorex.com
//
///////////////////////////////////////////////////////////////////////////////

using System;
using System.Collections.Generic;
using System.Text;
using System.Text.RegularExpressions;
using System.Drawing;
using System.Threading;
using WinForms = System.Windows.Forms;

using Ranorex;
using Ranorex.Core;
using Ranorex.Core.Testing;
using Ranorex.Core.Repository;

namespace MyTest21
{
#pragma warning disable 0436 //(CS0436) The type 'type' in 'assembly' conflicts with the imported type 'type2' in 'assembly'. Using the type defined in 'assembly'.
    /// <summary>
    ///The CreatePopups recording.
    /// </summary>
    [TestModule("de2ba2d5-4387-44bb-96ab-06a66666d314", ModuleType.Recording, 1)]
    public partial class CreatePopups : ITestModule
    {
        /// <summary>
        /// Holds an instance of the MyTest21Repository repository.
        /// </summary>
        public static MyTest21Repository repo = MyTest21Repository.Instance;

        static CreatePopups instance = new CreatePopups();

        /// <summary>
        /// Constructs a new instance.
        /// </summary>
        public CreatePopups()
        {
        }

        /// <summary>
        /// Gets a static instance of this recording.
        /// </summary>
        public static CreatePopups Instance
        {
            get { return instance; }
        }

#region Variables

#endregion

        /// <summary>
        /// Starts the replay of the static recording <see cref="Instance"/>.
        /// </summary>
        [System.CodeDom.Compiler.GeneratedCode("Ranorex", global::Ranorex.Core.Constants.CodeGenVersion)]
        public static void Start()
        {
            TestModuleRunner.Run(Instance);
        }

        /// <summary>
        /// Performs the playback of actions in this recording.
        /// </summary>
        /// <remarks>You should not call this method directly, instead pass the module
        /// instance to the <see cref="TestModuleRunner.Run(ITestModule)"/> method
        /// that will in turn invoke this method.</remarks>
        [System.CodeDom.Compiler.GeneratedCode("Ranorex", global::Ranorex.Core.Constants.CodeGenVersion)]
        void ITestModule.Run()
        {
            Mouse.DefaultMoveTime = 300;
            Keyboard.DefaultKeyPressTime = 20;
            Delay.SpeedFactor = 1.00;

            Init();

            Report.Log(ReportLevel.Info, "Application", "Run application 'C:\\Users\\Timothy McDoniel\\Documents\\Demo\\PopupGenerator.exe' in normal mode.", new RecordItemIndex(0));
            Host.Local.RunApplication("C:\\Users\\Timothy McDoniel\\Documents\\Demo\\PopupGenerator.exe", "", "C:\\Users\\Timothy McDoniel\\Documents\\Demo", false);
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'Form1.CheckBox1' at Center.", repo.Form1.CheckBox1Info, new RecordItemIndex(1));
            repo.Form1.CheckBox1.Click();
            Delay.Milliseconds(0);
            
        }

#region Image Feature Data
#endregion
    }
#pragma warning restore 0436
}
