///////////////////////////////////////////////////////////////////////////////
//
// This file was automatically generated by RANOREX.
// DO NOT MODIFY THIS FILE! It is regenerated by the designer.
// All your modifications will be lost!
// http://www.ranorex.com
//
///////////////////////////////////////////////////////////////////////////////

using System;
using System.Collections.Generic;
using System.Text;
using System.Drawing;
using Ranorex;
using Ranorex.Core;
using Ranorex.Core.Repository;
using Ranorex.Core.Testing;

namespace MyTest21
{
#pragma warning disable 0436 //(CS0436) The type 'type' in 'assembly' conflicts with the imported type 'type2' in 'assembly'. Using the type defined in 'assembly'.
    /// <summary>
    /// The class representing the MyTest21Repository element repository.
    /// </summary>
    [System.CodeDom.Compiler.GeneratedCode("Ranorex", global::Ranorex.Core.Constants.CodeGenVersion)]
    [RepositoryFolder("166f73d0-9c60-4465-a9f0-22280902bee4")]
    public partial class MyTest21Repository : RepoGenBaseFolder
    {
        static MyTest21Repository instance = new MyTest21Repository();
        MyTest21RepositoryFolders.RanorexVIPDatabaseTestWebApplicatioAppFolder _ranorexvipdatabasetestwebapplicatio;
        MyTest21RepositoryFolders.Form1AppFolder _form1;
        MyTest21RepositoryFolders.DemoPopupAppFolder _demopopup;

        /// <summary>
        /// Gets the singleton class instance representing the MyTest21Repository element repository.
        /// </summary>
        [RepositoryFolder("166f73d0-9c60-4465-a9f0-22280902bee4")]
        public static MyTest21Repository Instance
        {
            get { return instance; }
        }

        /// <summary>
        /// Repository class constructor.
        /// </summary>
        public MyTest21Repository() 
            : base("MyTest21Repository", "/", null, 0, false, "166f73d0-9c60-4465-a9f0-22280902bee4", ".\\RepositoryImages\\MyTest21Repository166f73d0.rximgres")
        {
            _ranorexvipdatabasetestwebapplicatio = new MyTest21RepositoryFolders.RanorexVIPDatabaseTestWebApplicatioAppFolder(this);
            _form1 = new MyTest21RepositoryFolders.Form1AppFolder(this);
            _demopopup = new MyTest21RepositoryFolders.DemoPopupAppFolder(this);
        }

#region Variables

#endregion

        /// <summary>
        /// The Self item info.
        /// </summary>
        [RepositoryItemInfo("166f73d0-9c60-4465-a9f0-22280902bee4")]
        public virtual RepoItemInfo SelfInfo
        {
            get
            {
                return _selfInfo;
            }
        }

        /// <summary>
        /// The RanorexVIPDatabaseTestWebApplicatio folder.
        /// </summary>
        [RepositoryFolder("0b3b558d-65bd-49f4-9c02-299b60bd76c2")]
        public virtual MyTest21RepositoryFolders.RanorexVIPDatabaseTestWebApplicatioAppFolder RanorexVIPDatabaseTestWebApplicatio
        {
            get { return _ranorexvipdatabasetestwebapplicatio; }
        }

        /// <summary>
        /// The Form1 folder.
        /// </summary>
        [RepositoryFolder("8904b218-e50e-4ba0-b051-a93650c26977")]
        public virtual MyTest21RepositoryFolders.Form1AppFolder Form1
        {
            get { return _form1; }
        }

        /// <summary>
        /// The DemoPopup folder.
        /// </summary>
        [RepositoryFolder("eb80a611-734b-412b-a125-58b99b1f510b")]
        public virtual MyTest21RepositoryFolders.DemoPopupAppFolder DemoPopup
        {
            get { return _demopopup; }
        }
    }

    /// <summary>
    /// Inner folder classes.
    /// </summary>
    [System.CodeDom.Compiler.GeneratedCode("Ranorex", global::Ranorex.Core.Constants.CodeGenVersion)]
    public partial class MyTest21RepositoryFolders
    {
        /// <summary>
        /// The RanorexVIPDatabaseTestWebApplicatioAppFolder folder.
        /// </summary>
        [RepositoryFolder("0b3b558d-65bd-49f4-9c02-299b60bd76c2")]
        public partial class RanorexVIPDatabaseTestWebApplicatioAppFolder : RepoGenBaseFolder
        {
            RepoItemInfo _firstnameInfo;
            RepoItemInfo _sometdtagInfo;
            RepoItemInfo _lastnameInfo;
            RepoItemInfo _genderInfo;
            RepoItemInfo _movieInfo;
            RepoItemInfo _inputtagaddInfo;
            RepoItemInfo _clearInfo;

            /// <summary>
            /// Creates a new RanorexVIPDatabaseTestWebApplicatio  folder.
            /// </summary>
            public RanorexVIPDatabaseTestWebApplicatioAppFolder(RepoGenBaseFolder parentFolder) :
                    base("RanorexVIPDatabaseTestWebApplicatio", "/dom[@domain='www.ranorex.com']", parentFolder, 30000, null, false, "0b3b558d-65bd-49f4-9c02-299b60bd76c2", "")
            {
                _firstnameInfo = new RepoItemInfo(this, "FirstName", ".//input[#'FirstName']", "", 30000, null, "9a6de4e1-485d-4cf6-b273-6297383f50a6");
                _sometdtagInfo = new RepoItemInfo(this, "SomeTdTag", ".//div[#'Content']//form/table/tbody/tr/td[1]/table/tbody/tr[1]/td[2]", "", 30000, null, "5004a869-b423-4128-ba63-edb86b3c5b95");
                _lastnameInfo = new RepoItemInfo(this, "LastName", ".//input[#'LastName']", "", 30000, null, "968c5af6-fc81-47a5-b7c5-f45ba533f4e9");
                _genderInfo = new RepoItemInfo(this, "Gender", ".//td[#'gender']//input[@name='Gender' and @type='radio' and @value='male']", "", 30000, null, "50f08c9d-3722-4732-873b-057a30a083ea");
                _movieInfo = new RepoItemInfo(this, "Movie", ".//select[#'Category']/option[@value='Movie']", "", 30000, null, "bb0a88bf-5ff2-478c-ae95-f3424e214daa");
                _inputtagaddInfo = new RepoItemInfo(this, "InputTagAdd", ".//input[#'Add']", "", 30000, null, "66504ce1-54d5-44cd-95b5-5b84f1fc9e64");
                _clearInfo = new RepoItemInfo(this, "Clear", ".//input[#'Clear']", "", 30000, null, "fba110a6-65d0-4280-8495-507a3b33907d");
            }

            /// <summary>
            /// The Self item.
            /// </summary>
            [RepositoryItem("0b3b558d-65bd-49f4-9c02-299b60bd76c2")]
            public virtual Ranorex.WebDocument Self
            {
                get
                {
                    return _selfInfo.CreateAdapter<Ranorex.WebDocument>(true);
                }
            }

            /// <summary>
            /// The Self item info.
            /// </summary>
            [RepositoryItemInfo("0b3b558d-65bd-49f4-9c02-299b60bd76c2")]
            public virtual RepoItemInfo SelfInfo
            {
                get
                {
                    return _selfInfo;
                }
            }

            /// <summary>
            /// The FirstName item.
            /// </summary>
            [RepositoryItem("9a6de4e1-485d-4cf6-b273-6297383f50a6")]
            public virtual Ranorex.InputTag FirstName
            {
                get
                {
                    return _firstnameInfo.CreateAdapter<Ranorex.InputTag>(true);
                }
            }

            /// <summary>
            /// The FirstName item info.
            /// </summary>
            [RepositoryItemInfo("9a6de4e1-485d-4cf6-b273-6297383f50a6")]
            public virtual RepoItemInfo FirstNameInfo
            {
                get
                {
                    return _firstnameInfo;
                }
            }

            /// <summary>
            /// The SomeTdTag item.
            /// </summary>
            [RepositoryItem("5004a869-b423-4128-ba63-edb86b3c5b95")]
            public virtual Ranorex.TdTag SomeTdTag
            {
                get
                {
                    return _sometdtagInfo.CreateAdapter<Ranorex.TdTag>(true);
                }
            }

            /// <summary>
            /// The SomeTdTag item info.
            /// </summary>
            [RepositoryItemInfo("5004a869-b423-4128-ba63-edb86b3c5b95")]
            public virtual RepoItemInfo SomeTdTagInfo
            {
                get
                {
                    return _sometdtagInfo;
                }
            }

            /// <summary>
            /// The LastName item.
            /// </summary>
            [RepositoryItem("968c5af6-fc81-47a5-b7c5-f45ba533f4e9")]
            public virtual Ranorex.InputTag LastName
            {
                get
                {
                    return _lastnameInfo.CreateAdapter<Ranorex.InputTag>(true);
                }
            }

            /// <summary>
            /// The LastName item info.
            /// </summary>
            [RepositoryItemInfo("968c5af6-fc81-47a5-b7c5-f45ba533f4e9")]
            public virtual RepoItemInfo LastNameInfo
            {
                get
                {
                    return _lastnameInfo;
                }
            }

            /// <summary>
            /// The Gender item.
            /// </summary>
            [RepositoryItem("50f08c9d-3722-4732-873b-057a30a083ea")]
            public virtual Ranorex.InputTag Gender
            {
                get
                {
                    return _genderInfo.CreateAdapter<Ranorex.InputTag>(true);
                }
            }

            /// <summary>
            /// The Gender item info.
            /// </summary>
            [RepositoryItemInfo("50f08c9d-3722-4732-873b-057a30a083ea")]
            public virtual RepoItemInfo GenderInfo
            {
                get
                {
                    return _genderInfo;
                }
            }

            /// <summary>
            /// The Movie item.
            /// </summary>
            [RepositoryItem("bb0a88bf-5ff2-478c-ae95-f3424e214daa")]
            public virtual Ranorex.OptionTag Movie
            {
                get
                {
                    return _movieInfo.CreateAdapter<Ranorex.OptionTag>(true);
                }
            }

            /// <summary>
            /// The Movie item info.
            /// </summary>
            [RepositoryItemInfo("bb0a88bf-5ff2-478c-ae95-f3424e214daa")]
            public virtual RepoItemInfo MovieInfo
            {
                get
                {
                    return _movieInfo;
                }
            }

            /// <summary>
            /// The InputTagAdd item.
            /// </summary>
            [RepositoryItem("66504ce1-54d5-44cd-95b5-5b84f1fc9e64")]
            public virtual Ranorex.InputTag InputTagAdd
            {
                get
                {
                    return _inputtagaddInfo.CreateAdapter<Ranorex.InputTag>(true);
                }
            }

            /// <summary>
            /// The InputTagAdd item info.
            /// </summary>
            [RepositoryItemInfo("66504ce1-54d5-44cd-95b5-5b84f1fc9e64")]
            public virtual RepoItemInfo InputTagAddInfo
            {
                get
                {
                    return _inputtagaddInfo;
                }
            }

            /// <summary>
            /// The Clear item.
            /// </summary>
            [RepositoryItem("fba110a6-65d0-4280-8495-507a3b33907d")]
            public virtual Ranorex.InputTag Clear
            {
                get
                {
                    return _clearInfo.CreateAdapter<Ranorex.InputTag>(true);
                }
            }

            /// <summary>
            /// The Clear item info.
            /// </summary>
            [RepositoryItemInfo("fba110a6-65d0-4280-8495-507a3b33907d")]
            public virtual RepoItemInfo ClearInfo
            {
                get
                {
                    return _clearInfo;
                }
            }
        }

        /// <summary>
        /// The Form1AppFolder folder.
        /// </summary>
        [RepositoryFolder("8904b218-e50e-4ba0-b051-a93650c26977")]
        public partial class Form1AppFolder : RepoGenBaseFolder
        {
            RepoItemInfo _checkbox1Info;

            /// <summary>
            /// Creates a new Form1  folder.
            /// </summary>
            public Form1AppFolder(RepoGenBaseFolder parentFolder) :
                    base("Form1", "/form[@controlname='Form1']", parentFolder, 30000, null, true, "8904b218-e50e-4ba0-b051-a93650c26977", "")
            {
                _checkbox1Info = new RepoItemInfo(this, "CheckBox1", "checkbox[@controlname='CheckBox1']", "", 30000, null, "bf28b9a5-dd02-4bf6-a1c5-d10f26dca6d8");
            }

            /// <summary>
            /// The Self item.
            /// </summary>
            [RepositoryItem("8904b218-e50e-4ba0-b051-a93650c26977")]
            public virtual Ranorex.Form Self
            {
                get
                {
                    return _selfInfo.CreateAdapter<Ranorex.Form>(true);
                }
            }

            /// <summary>
            /// The Self item info.
            /// </summary>
            [RepositoryItemInfo("8904b218-e50e-4ba0-b051-a93650c26977")]
            public virtual RepoItemInfo SelfInfo
            {
                get
                {
                    return _selfInfo;
                }
            }

            /// <summary>
            /// The CheckBox1 item.
            /// </summary>
            [RepositoryItem("bf28b9a5-dd02-4bf6-a1c5-d10f26dca6d8")]
            public virtual Ranorex.CheckBox CheckBox1
            {
                get
                {
                    return _checkbox1Info.CreateAdapter<Ranorex.CheckBox>(true);
                }
            }

            /// <summary>
            /// The CheckBox1 item info.
            /// </summary>
            [RepositoryItemInfo("bf28b9a5-dd02-4bf6-a1c5-d10f26dca6d8")]
            public virtual RepoItemInfo CheckBox1Info
            {
                get
                {
                    return _checkbox1Info;
                }
            }
        }

        /// <summary>
        /// The DemoPopupAppFolder folder.
        /// </summary>
        [RepositoryFolder("eb80a611-734b-412b-a125-58b99b1f510b")]
        public partial class DemoPopupAppFolder : RepoGenBaseFolder
        {
            RepoItemInfo _okbuttonInfo;

            /// <summary>
            /// Creates a new DemoPopup  folder.
            /// </summary>
            public DemoPopupAppFolder(RepoGenBaseFolder parentFolder) :
                    base("DemoPopup", "/form[@controlname='DemoPopup']", parentFolder, 30000, null, true, "eb80a611-734b-412b-a125-58b99b1f510b", "")
            {
                _okbuttonInfo = new RepoItemInfo(this, "OKButton", "?/?/button[@controlname='OK_Button']", "", 30000, null, "ab148afa-aed5-4205-830f-53c0c47e86ed");
            }

            /// <summary>
            /// The Self item.
            /// </summary>
            [RepositoryItem("eb80a611-734b-412b-a125-58b99b1f510b")]
            public virtual Ranorex.Form Self
            {
                get
                {
                    return _selfInfo.CreateAdapter<Ranorex.Form>(true);
                }
            }

            /// <summary>
            /// The Self item info.
            /// </summary>
            [RepositoryItemInfo("eb80a611-734b-412b-a125-58b99b1f510b")]
            public virtual RepoItemInfo SelfInfo
            {
                get
                {
                    return _selfInfo;
                }
            }

            /// <summary>
            /// The OKButton item.
            /// </summary>
            [RepositoryItem("ab148afa-aed5-4205-830f-53c0c47e86ed")]
            public virtual Ranorex.Button OKButton
            {
                get
                {
                    return _okbuttonInfo.CreateAdapter<Ranorex.Button>(true);
                }
            }

            /// <summary>
            /// The OKButton item info.
            /// </summary>
            [RepositoryItemInfo("ab148afa-aed5-4205-830f-53c0c47e86ed")]
            public virtual RepoItemInfo OKButtonInfo
            {
                get
                {
                    return _okbuttonInfo;
                }
            }
        }

    }
#pragma warning restore 0436
}
